### PR TITLE
Fix Python runtime error

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by bitsgalore** [comment]
Hi Stefan,

First of all many thanks for the patch! Could you perhaps supply a JP2 that produces the error you're reporting, as that would help me to review the patch.

BTW I'm in the middle of some major computer crisis at the moment (main development machine utterly fried), so it may take me a while to have a proper look at this).

**Comment by stweil** [comment]
Hi Johan,

a test file is available from http://weilnetz.de/triggerUnboundLocalError.jp2.
It was created by kdu_compress from a TIFF file, but obviously the conversion failed.

I have now updated my patch, so jpylyzer can handle this file.

Stefan

**Comment by bitsgalore** [comment]
Hi Stefan,

I finally merged your patch. One additional question: would you mind if I include your test file in the jpylyzer test corpus (link: <https://github.com/openpreserve/jpylyzer-test-files>)?

Thanks again!

Johan

**Comment by stweil** [comment]
Hi Johan,

you may do so - thanks for jpylyzer and your work. I'm glad if I can help a little bit.

Stefan

**Comment by bitsgalore** [comment]
Thanks Stefan, I just added the file (with proper credit of course)

**Pull request merged**
